name: Firebase Deploy
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Create .env file
        run: |
          cd client
          cp .env.production .env
          sed -i "s|\${NEXT_PUBLIC_FIREBASE_API_KEY}|${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}|g" .env
          sed -i "s|\${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}|${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}|g" .env
          sed -i "s|\${NEXT_PUBLIC_FIREBASE_APP_ID}|${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}|g" .env
          sed -i "s|\${FIREBASE_CLIENT_EMAIL}|${{ secrets.FIREBASE_CLIENT_EMAIL }}|g" .env
          sed -i "s|\${FIREBASE_PRIVATE_KEY}|${{ secrets.FIREBASE_PRIVATE_KEY }}|g" .env
          sed -i "s|\${OPENAI_API_KEY}|${{ secrets.OPENAI_API_KEY }}|g" .env
      
      - name: Install Client Dependencies
        run: cd client && npm ci
      
      - name: Build Client
        run: cd client && npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: 'klumsiland'